# Generated by Django 5.2.4 on 2025-08-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_a', to='category.category')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to_b', to='category.category')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category_a', 'category_b'), name='unique_similarity'), models.CheckConstraint(condition=models.Q(('category_a', models.F('category_b')), _negated=True), name='no_self_similarity')],
            },
        ),
    ]
