# Generated by Django 5.2.4 on 2025-08-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_dummymodel_alter_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='similarity',
            options={'verbose_name': 'Similarity', 'verbose_name_plural': 'Similarities'},
        ),
    ]
